<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <!-- laser component -->
    <xacro:property name="stents_radius" value="0.01" />
    <xacro:property name="stents_length" value="0.15" />
    <xacro:property name="laser_radius" value="0.03" />
    <xacro:property name="laser_length" value="0.05" />

    <xacro:property name="joint_stents_x" value="0" />
    <xacro:property name="joint_stents_y" value="0" />
    <xacro:property name="joint_stents_z" value="${base_length / 2 + stents_length / 2}" />
    <xacro:property name="joint_laser_x" value="0" />
    <xacro:property name="joint_laser_y" value="0" />
    <xacro:property name="joint_laser_z" value="${laser_length / 2 + stents_length / 2}" />
    <!-- 1.stents -->
    <link name="stents">
        <visual>
            <geometry>
                <cylinder radius="${stents_radius}" length="${stents_length}" />
            </geometry>

            <material name="yellow">
                <color rgba="0.8 0.5 0.0 0.5" />
            </material>
        </visual>
    </link>
    <joint name="stents2base" type="fixed">
        <parent link="base_link" />
        <child link="stents" />
        <origin xyz="${joint_stents_x} ${joint_stents_y} ${joint_stents_z}" rpy="0 0 0" />
    </joint>
    <!-- 2.laser -->
    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>

            <material name="black">
                <color rgba="0 0 0 0.5" />
            </material>
        </visual>
    </link>
    <joint name="laser2stents" type="fixed">
        <parent link="stents" />
        <child link="laser" />
        <origin xyz="${joint_laser_x} ${joint_laser_y} ${joint_laser_z}" rpy="0 0 0" />
    </joint>
</robot>