// Generated by gencpp from file pluming_server_client/AddInts.msg
// DO NOT EDIT!


#ifndef PLUMING_SERVER_CLIENT_MESSAGE_ADDINTS_H
#define PLUMING_SERVER_CLIENT_MESSAGE_ADDINTS_H

#include <ros/service_traits.h>


#include <pluming_server_client/AddIntsRequest.h>
#include <pluming_server_client/AddIntsResponse.h>


namespace pluming_server_client
{

struct AddInts
{

typedef AddIntsRequest Request;
typedef AddIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddInts
} // namespace pluming_server_client


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pluming_server_client::AddInts > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::pluming_server_client::AddInts&) { return value(); }
};

template<>
struct DataType< ::pluming_server_client::AddInts > {
  static const char* value()
  {
    return "pluming_server_client/AddInts";
  }

  static const char* value(const ::pluming_server_client::AddInts&) { return value(); }
};


// service_traits::MD5Sum< ::pluming_server_client::AddIntsRequest> should match
// service_traits::MD5Sum< ::pluming_server_client::AddInts >
template<>
struct MD5Sum< ::pluming_server_client::AddIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pluming_server_client::AddInts >::value();
  }
  static const char* value(const ::pluming_server_client::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pluming_server_client::AddIntsRequest> should match
// service_traits::DataType< ::pluming_server_client::AddInts >
template<>
struct DataType< ::pluming_server_client::AddIntsRequest>
{
  static const char* value()
  {
    return DataType< ::pluming_server_client::AddInts >::value();
  }
  static const char* value(const ::pluming_server_client::AddIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pluming_server_client::AddIntsResponse> should match
// service_traits::MD5Sum< ::pluming_server_client::AddInts >
template<>
struct MD5Sum< ::pluming_server_client::AddIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pluming_server_client::AddInts >::value();
  }
  static const char* value(const ::pluming_server_client::AddIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pluming_server_client::AddIntsResponse> should match
// service_traits::DataType< ::pluming_server_client::AddInts >
template<>
struct DataType< ::pluming_server_client::AddIntsResponse>
{
  static const char* value()
  {
    return DataType< ::pluming_server_client::AddInts >::value();
  }
  static const char* value(const ::pluming_server_client::AddIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLUMING_SERVER_CLIENT_MESSAGE_ADDINTS_H
